### ISSUE TITLE
what are plug-in components?

### ISSUE THREAD

**Issue by ShortsKing** [ashleynewson/SmartSim#13]
this isnt much of an issue but rather a question: what are plug-in components?
i know i have made many components, but i have never uncovered what plug-in components are. the button has been annoying me for so long i gave up resisting and came here. thanks!

**Comment by ashleynewson** [comment]
Plug-in components are components that are implemented via software libraries (i.e. DLLs on Windows or .so files on Linux). They were introduced to allow others to implement components which can't be created using the built-in set of components, and don't belong with the standard set of built-in components.

However, to my knowledge, they aren't widely used, and there generally isn't any need to use them. The only significant plug-in component I ever created was a component which could interface with the GPIO pins on (for example) a Raspberry Pi, allowing the simulated circuit to interact with real-life hardware.
