### ISSUE TITLE
new project can't add projects

### ISSUE THREAD

**Issue by chriscamacho** [ashleynewson/SmartSim#3]
I cloned and compiled without fault then ran make install on latest ubuntu 64bit

when starting or selecting new project I see only a grey window with "welcome to smartsim"

There seems no way to add any of the components or create any kind of circuit

in order to edit / create a circuit I have to load in an existing circuit...

**Comment by wraybowling** [comment]
This is a **VERY SERIOUS** usability issue. All new projects should start with a new component. I clicked around on everything I could think of not understanding how to get past "Welcome to SmartSim" for about 10 minutes.

Please re-open this ticket.
