### ISSUE TITLE
SmartSim on Windows7, 64-bit machine?

### ISSUE THREAD

**Issue by rharbird** [ashleynewson/SmartSim#6]
Hi,

I'm having issues with SmartSim running on a  64-bit machine with the Windows 7 operating system. Specifically, if I want to click on an icon on the toolbar, I have to click outside the SmartSim GUI and then click on the required icon. So, say the active icon is the AND gate. If I click on the Bin icon directly, nothing happens. If I click anywhere on my desktop and then on the bin icon it works.

Any ideas?

**Comment by ashleynewson** [comment]
This issue is old, and was not reproducible.

Reopen if necessary
